export default [
  'transition',
  'transition-property',
  'transition-delay',
  'transition-timing-function',
  'transition-duration',
  'animation',
  'animation-name',
  'animation-duration',
  'animation-play-state',
  'animation-timing-function',
  'animation-delay',
  'animation-iteration-count',
  'animation-direction',
  'animation-fill-mode',
];
